# Generated by Django 5.2.1 on 2025-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
