# Generated by Django 5.2.1 on 2025-05-26 14:29

import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_otp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[utils.validations.validate_phone]),
        ),
    ]
