# Generated by Django 5.2.1 on 2025-05-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-created', 'end_time')},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='craeted',
            new_name='created',
        ),
    ]
