# Generated by Django 5.2.1 on 2025-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_rename_choice_vote_choice_alter_poll_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=120),
        ),
    ]
